name: build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    env:
      PATH_APPLICATION_SLN: SimpleVolumeMixer.sln
      PATH_APPLICATION_CSPROJ: SimpleVolumeMixer\SimpleVolumeMixer.csproj
      BUILD_CONFIGURATION_NAME: Release
      BUILD_PLATFORM_TYPE: "Any CPU"

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          5.x
          6.x
    
    - name: restore dependencies
      shell: pwsh
      run: dotnet restore $Env:GITHUB_WORKSPACE\${{ env.PATH_APPLICATION_SLN }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: Build
      shell: pwsh
      run: dotnet build $Env:GITHUB_WORKSPACE\${{ env.PATH_APPLICATION_CSPROJ }} --configuration ${{ env.BUILD_CONFIGURATION_NAME }} --no-restore -p:Platform=${{ env.BUILD_PLATFORM_TYPE }}
