name: build

on: [push]

jobs:
  build:

    runs-on: windows-2019
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - run: (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=2088517', 'ndp48-devpack-enu.exe')
    - run: .\ndp48-devpack-enu.exe /passive /norestart
    - run: nuget restore $Env:GITHUB_WORKSPACE\SimpleVolumeMixer\SimpleVolumeMixer.csproj
    - uses: warrenbuckley/Setup-MSBuild@v1
    - run: MSBuild.exe -p:Configuration=Release -m -t:Build $Env:GITHUB_WORKSPACE\SimpleVolumeMixer\SimpleVolumeMixer.csproj
      timeout-minutes: 5
