name: build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    env:
      PATH_APPLICATION_CSPROJ: $Env:GITHUB_WORKSPACE\SimpleVolumeMixer\SimpleVolumeMixer.csproj
      BUILD_CONFIGURATION_NAME: Release
      BUILD_PLATFORM_TYPE: "Any CPU"

    steps:
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          4.x
    
    - name: restore dependencies
      shell: pwsh
      run: dotnet restore $Env:PATH_APPLICATION_CSPROJ

    - name: Build
      shell: pwsh
      run: dotnet build $Env:PATH_APPLICATION_CSPROJ --configuration $Env:BUILD_CONFIGURATION_NAME --no-restore -p:Platform=$Env:BUILD_PLATFORM_TYPE
