name: build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      PATH_APPLICATION_SLN: SimpleVolumeMixer.sln
      PATH_APPLICATION_CSPROJ: SimpleVolumeMixer\SimpleVolumeMixer.csproj
      BUILD_CONFIGURATION_NAME: Release
      BUILD_PLATFORM_TYPE: "Any CPU"

    steps:
    - name: pwd
      run: |
        echo ${Env:GITHUB_WORKSPACE}
        dir
    
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          5.x
          6.x
    
    - name: checkout this solution
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: restore dependencies
      shell: pwsh
      run: dotnet restore ${Env:GITHUB_WORKSPACE}\${{ env.PATH_APPLICATION_SLN }}
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: build
      shell: pwsh
      run: dotnet build ${Env:GITHUB_WORKSPACE}\${{ env.PATH_APPLICATION_CSPROJ }} --configuration ${{ env.BUILD_CONFIGURATION_NAME }} --no-restore -p:Platform="${{ env.BUILD_PLATFORM_TYPE }}"
      
    - name: dir
      shell: pwsh
      run: |
        dir ${{ github.workspace }}\SimpleVolumeMixer
        dir ${{ github.workspace }}\SimpleVolumeMixer\bin
        dor ${{ github.workspace }}\SimpleVolumeMixer\bin\Release
      
    - name: collect artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: SimpleVolumeMixer
        path: ${{ github.workspace }}\SimpleVolumeMixer\bin\Release
      
