name: create a release pull request

on:
  workflow_call: 
    
  pull_request:
    types: [ closed ]
    branches:
      - develop

env:
  pathOfVersioning: ${{ github.workspace }}\SimpleVolumeMixer

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:

      - name: checkout this solution
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup versioning
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
          path: ${{ env.pathOfVersioning }}

      - name: create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          APP_VERSION: v${{ steps.nbgv.outputs.NuGetPackageVersion }}
          GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template